### ISSUE TITLE
flattenAddtionalValues generated during helm import does not handle arrays correctly

### ISSUE THREAD

**Issue by BoatPartyJesus** [cdk8s-team/cdk8s-cli#1538]
### Description of the bug:
After importing a helm chart, and adding array values and running `synth` I found that the yaml that is generated is incorrect, it creates a map instead of a list. In this instance, I am using the minio operator chart, but I've tried with a couple of others, examples below.

### Reproduction Steps:

cdk8s.yml
```yaml
language: typescript
app: npx ts-node main.ts
imports:
  - k8s
  - minio:=helm:https://operator.min.io/operator@5.0.9
  - helm:https://grafana.github.io/helm-charts/loki@5.27.0
```

MINio chart
```typescript
export class MyChart extends Chart {
  constructor(scope: Construct, id: string, props: ChartProps = {}) {
    super(scope, id, props);

    new MinioOperator(this, "minio-operator", {
      values: {
        operator: {
          replicaCount: 1,
          volumes: [
            {
              mountPath: "/tmp/certs",
              name: "tls-minio",
            },
          ],
          volumeMounts: [
            {
              name: "tls-minio",
              projected: {
                defaultMode: 420,
                sources: [
                  {
                    secret: {
                      name: "tls-minio",
                      items: [
                        {
                          key: "tls.crt",
                          path: "CAs/custom-public.crt",
                        },
                      ],
                    },
                  },
                  {
                    secret: {
                      name: "tls-minio",
                      items: [
                        {
                          key: "tls.crt",
                          path: "CAs/custom-public.crt",
                        },
                      ],
                    },
                  },
                ],
              },
            },
          ],
        },
      },
    });
  }
}
```

synth output:
```yaml
---
volumeMounts:
  "0":
    name: tls-minio
    projected:
      defaultMode: 420
      sources:
        "0":
          secret:
            items:
              "0":
                key: tls.crt
                path: CAs/custom-public.crt
            name: tls-minio
        "1":
          secret:
            items:
              "0":
                key: tls.crt
                path: CAs/custom-public.crt
            name: tls-minio
---
volumes:
  "0":
    mountPath: /tmp/certs
    name: tls-minio
```

The same happens with Loki, but this time I get an error message in console instead of a synthed chart

Chart
```yaml
export class MyChart extends Chart {
  constructor(scope: Construct, id: string, props: ChartProps = {}) {
    super(scope, id, props);

    new Loki(this, "loki", {
      releaseName: "loki",
      values: {
        loki: {
          auth_enabled: false,
          replication_enabled: false,
        },
        common_config: {
          replication_factor: 1,
        },
        write: {
          replicas: 1,
        },
        read: {
          replicas: 1,
        },
        backend: {
          replicas: 1,
          extraVolumes: [
            {
              mountPath: "/tmp/certs",
              name: "tls-minio",
            },
          ],
        },
        test: {
          enabled: false,
        },
      },
    });
  }
}
```

### Error Log:
```
...\cdk8s\src\helm.ts:152
    throw new Error(helm.stderr.toString());
          ^
Error: coalesce.go:223: warning: destination for loki.backend.extraVolumes is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for loki.backend.extraVolumes is a table. Ignoring non-table value ([])
Error: YAML parse error on loki/templates/backend/statefulset-backend.yaml: error converting YAML to JSON: yaml: line 137: did not find expected '-' indicator
```

### Environment:

  - **Framework Version**: 2.138.0
  - **OS**: Windows 22H2 Build 22621.2428 

### Other:
After reviewing the `flattenAdditionaValues` function in the generated import it looks as though arrays are not explicitly handled, maybe something like this inside the for loop:

```typescript
for (let prop in props) {
    if (Array.isArray(props[prop])) {
      output[prop] = props[prop].map(item => {
        if (typeof item === 'object') {
          return this.flattenAdditionalValues(item);
        }
        return item;
      });
    } 
    else if (typeof(props[prop]) === 'object' && prop !== 'additionalValues') {
      output[prop] = this.flattenAdditionalValues(props[prop]);
    } 
    else {
      output[prop] = props[prop];
    }
  }
```
---

This is :bug: Bug Report
