### ISSUE TITLE
Add homebrew release

### ISSUE THREAD

**Issue by eladb** [cdk8s-team/cdk8s-cli#2]
From the original mono-repository:

```yaml

  release_homebrew:
    name: Release to Homebrew
    # The branch or tag ref that triggered the workflow run.
    if: startsWith(github.event.head_commit.message, 'chore(release)') && contains(github.event.head_commit.message, 'beta') == false
    needs: release_npm
    runs-on: ubuntu-latest
    steps:
      # extract version number from package.json
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: tools/install-workflow-deps.sh
      - name: set version
        run: tools/align-version.sh
      - name: version
        id: get_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "::set-output name=version::${version}"

      # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: cdk8s
          download-url: https://registry.npmjs.org/cdk8s-cli/-/cdk8s-cli-${{ steps.get_version.outputs.version }}.tgz
          commit-message: cdk8s ${{ steps.get_version.outputs.version }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}
```
