### ISSUE TITLE
Generated Props schemas field ordering does not match expectations from cdk8s-core

### ISSUE THREAD

**Issue by heckler1** [cdk8s-team/cdk8s-cli#323]
Per https://github.com/cdk8s-team/cdk8s-core/blob/58fb8c0882ddd95a9b9dedb4107e12f601443cf4/src/api-object.ts#L185, it looks like we expect that the `ApiVersion`, `Kind`, and `Metadata` fields are populated first, and placed at the top of a generated YAML document.

At one point in the past, this was the behavior, but with the introduction of per-object `toJson_...` functions, this behavior changed. Now, the ordering of the fields matches whatever is in the K8S API schemas in cdk8s/kubernetes-schemas.

My expectation is that the behavior of the generated `toJson_` functions would match the `ApiObject.toJson()` function's behavior.

Expected manifest:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: myservice
  name: my-config-map
  namespace: myservice
data:
  mydata: goes here
```

Actual manifest:
```
apiVersion: v1
kind: ConfigMap
data:
  mydata: goes here
metadata:
  labels:
    app: myservice
  name: my-config-map
  namespace: myservice
```

Especially in the case of config maps. longer data will force the metadata off screen and makes reading generated manifests more difficult and error prone.
