### ISSUE TITLE
Validation plugins mechanism

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-cli#460]
As part of https://github.com/cdk8s-team/cdk8s/discussions/936, we need the CLI to support a basic plugin mechanism for third-parties to implement validation plugins:

Example potential configuration:

```yaml
validations:
  - package: cdk8s-datree-plugin
    class: DatreeValidation
    properties:
      policy: ./my-policy.json
```

This configuration can also be located in a remote URL or a local file:

```yaml
validations: /path/to/file
```

```yaml
validations: http://url/to/file
```

In this case, the contents of the file should be fetched.

The plugin mechanism should:

1. Define the interface plugins should implement.
2. Be able to dynamically load/instantiate classes and call a well known method on them.
3. Wait for the plugin to return a result, and print a report to the user.
