### ISSUE TITLE
Importing multiple CRD manifests from same source only imports the last

### ISSUE THREAD

**Issue by TobbenTM** [cdk8s-team/cdk8s-cli#696]
Given the following `cdk8s.yaml`:

```yaml
language: typescript
app: node main.js
imports:
  - k8s@1.23.0
  - https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/crd-certificates.yaml
  - https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/crd-clusterissuers.yaml
```

The CLI will create a `cert-manager.io.ts` file, but that'll only actually contain the cluster issuers, not the certificates.

I'm assuming this is because it's overriding the previous certificate import with the one that is imported last, but this cannot be the intended behavior right? Is there something I'm doing wrong, or is this an actual bug? Assigning them different names works, but also produces rather ugly file names.
